core/urls.py
from django.urls import path
from .views import (
    BookingListViewAdmin,
    CreateBookingView,
    UpdateBookingViewAdmin,
    UpdateVerificationiViewAdmin,
    BookingListView,
    VerificationListViewAdmin,
    BookingSuccessfulView,
)

app_name = "core"
urlpatterns = [
    path("create-booking/", CreateBookingView.as_view(), name="create-booking"),
    path(
        "booking-successful/",
        BookingSuccessfulView.as_view(),
        name="booking-successful",
    ),
    path(
        "update-verification/<str:resident_id>/",
        UpdateVerificationiViewAdmin.as_view(),
        name="update-verification-admin",
    ),
    path(
        "update-booking/<str:booking_id>/",
        UpdateBookingViewAdmin.as_view(),
        name="update-booking-admin",
    ),
    path("my-bookings/", BookingListView.as_view(), name="my-bookings"),
    path(
        "all-verifications/",
        VerificationListViewAdmin.as_view(),
        name="verification-list-admin",
    ),
    path(
        "all-bookings/",
        BookingListViewAdmin.as_view(),
        name="booking-list-admin",
    ),
]

home/urls.py
from django.urls import path
from .views import home

app_name = "home"
urlpatterns = [
    path("", home, name="home"),
]

room/urls.py
from django.urls import path
from .views import AddRoomViewAdmin, RoomListView, RoomDetailView, UpdateRoomViewAdmin

app_name = "room"
urlpatterns = [
    path("floor/<str:floor>/", RoomListView.as_view(), name="room-list"),
    path(
        "floor/<str:floor>/room-add/", AddRoomViewAdmin.as_view(), name="room-add-admin"
    ),
    path(
        "floor/<str:floor>/<str:room_number>/",
        RoomDetailView.as_view(),
        name="room-detail",
    ),
    path(
        "floor/<str:floor>/<str:room_number>/room-update/",
        UpdateRoomViewAdmin.as_view(),
        name="room-update-admin",
    ),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import (
    CreateUserView,
    ResidentListViewAdmin,
    ResidentUpdateView,
    ResidentDetailView,
    DashboardViewAdmin,
    ResidentUpdateViewAdmin,
)

from core.views import CreateResidentVerificationView

app_name = "user"
urlpatterns = [
    path("register/", CreateUserView.as_view(), name="user-register"),
    path(
        "login/", LoginView.as_view(template_name="user/login.html"), name="user-login"
    ),
    path(
        "logout/",
        LogoutView.as_view(template_name="user/logout.html"),
        name="user-logout",
    ),
    path("update/<slug:resident_id>", ResidentUpdateView.as_view(), name="user-update"),
    path(
        "verification/",
        CreateResidentVerificationView.as_view(),
        name="user-verification",
    ),
    # paths for admin user
    path("admin/dashboard/", DashboardViewAdmin.as_view(), name="admin-dashboard"),
    path("admin/all-users/", ResidentListViewAdmin.as_view(), name="user-list-admin"),
    path(
        "admin/update/<slug:resident_id>/",
        ResidentUpdateViewAdmin.as_view(),
        name="user-update-admin",
    ),
    ########################
    path("<int:resident_id>/", ResidentDetailView.as_view(), name="user-detail"),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, "home/home.html")

home/templates/home/home.html
<h1>Welcome {% if user.is_authenticated %} {{user.first_name}} {% else %} Dormmy {% endif %}</h1>
----------------------------------------------------------
<h2>DormDelight</h2>
<h2><a href="#">Rooms</a></h2>
<h2><a href="#">Facilities</a></h2>
<h2><a href="#">About</a></h2>
{% if user.is_authenticated %}
    {% if user.is_admin %}
        <h2><a href="{% url 'user:admin-dashboard' %}">Dashboard</a></h2>
    {% else %}
        <h2><a href="{% url 'user:user-detail' user.resident.resident_id %}">Profile</a></h2>
    {% endif %}
{% else %}
    <h2><a href="{% url 'user:user-login' %}">Login</a></h2>
{% endif %}
----------------------------------------------------------
<h2><a href="{% url 'room:room-list' 1 %}">F1</a></h2>
<h2><a href="{% url 'room:room-list' 2 %}">F2</a></h2>
<h2><a href="{% url 'room:room-list' 3 %}">F3</a></h2>
<h2><a href="{% url 'room:room-list' 4 %}">F4</a></h2>
----------------------------------------------------------
<h1>Facilities</h1>
----------------------------------------------------------
<h1>Contact</h1>
----------------------------------------------------------