core/urls.py
from django.urls import path
from .views import (
    BookingListViewAdmin,
    CreateBookingView,
    UpdateBookingViewAdmin,
    UpdateVerificationiViewAdmin,
    BookingListView,
    VerificationListViewAdmin,
    BookingSuccessfulView,
)

app_name = "core"
urlpatterns = [
    path("create-booking/", CreateBookingView.as_view(), name="create-booking"),
    path(
        "booking-successful/",
        BookingSuccessfulView.as_view(),
        name="booking-successful",
    ),
    path(
        "update-verification/<str:resident_id>/",
        UpdateVerificationiViewAdmin.as_view(),
        name="update-verification-admin",
    ),
    path(
        "update-booking/<str:booking_id>/",
        UpdateBookingViewAdmin.as_view(),
        name="update-booking-admin",
    ),
    path("my-bookings/", BookingListView.as_view(), name="my-bookings"),
    path(
        "all-verifications/",
        VerificationListViewAdmin.as_view(),
        name="verification-list-admin",
    ),
    path(
        "all-bookings/",
        BookingListViewAdmin.as_view(),
        name="booking-list-admin",
    ),
]

home/urls.py
from django.urls import path
from .views import home

app_name = "home"
urlpatterns = [
    path("", home, name="home"),
]

room/urls.py
from django.urls import path
from .views import AddRoomViewAdmin, RoomListView, RoomDetailView, UpdateRoomViewAdmin

app_name = "room"
urlpatterns = [
    path("floor/<str:floor>/", RoomListView.as_view(), name="room-list"),
    path(
        "floor/<str:floor>/room-add/", AddRoomViewAdmin.as_view(), name="room-add-admin"
    ),
    path(
        "floor/<str:floor>/<str:room_number>/",
        RoomDetailView.as_view(),
        name="room-detail",
    ),
    path(
        "floor/<str:floor>/<str:room_number>/room-update/",
        UpdateRoomViewAdmin.as_view(),
        name="room-update-admin",
    ),
]

room/models.py
from django.db import models

# Create your models here.
class Room(models.Model):
    FLOOR_CHOICES = [
        ("1", "First"),
        ("2", "Second"),
        ("3", "Third"),
        ("4", "Fourth"),
    ]
    TYPE_CHOICES = [
        ("1", "Single"),
        ("2", "Double"),
        ("3", "Triple"),
    ]
    room_number = models.CharField(max_length=3, primary_key=True, unique=True)
    floor = models.CharField(max_length=1, choices=FLOOR_CHOICES)
    type = models.CharField(max_length=1, choices=TYPE_CHOICES)
    ac = models.BooleanField(null=True, blank=True)
    rent = models.DecimalField(max_digits=7, decimal_places=2)
    occupied = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.room_number}"

    @classmethod
    def get_unoccupied_rooms(cls):
        return cls.objects.filter(occupied=False)

room/views.py
from django.shortcuts import reverse
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from user.mixins import AdminUserTestMixin

from .models import Room

# Create your views here.
class RoomListView(ListView):
    model = Room

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context["room_list"] = (
            context["room_list"]
            .filter(floor=self.kwargs.get("floor"))
            .order_by("occupied")
        )
        context["floor"] = self.kwargs.get("floor")
        return context


class RoomDetailView(DetailView):
    model = Room
    pk_url_kwarg = "room_number"


class AddRoomViewAdmin(LoginRequiredMixin, AdminUserTestMixin, CreateView):
    model = Room
    fields = ["room_number", "type", "ac", "rent", "occupied"]
    template_name = "room/admin/room_form_admin.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["floor"] = self.kwargs.get("floor")
        return context

    def form_valid(self, form):
        form.instance.floor = self.kwargs.get("floor")
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            "room:room-detail", args=[self.object.floor, self.object.room_number]
        )


class UpdateRoomViewAdmin(LoginRequiredMixin, AdminUserTestMixin, UpdateView):
    model = Room
    fields = ["type", "ac", "rent", "occupied"]
    template_name = "room/admin/room_form_admin.html"
    pk_url_kwarg = "room_number"

    def get_success_url(self):
        return reverse(
            "room:room-detail", args=[self.object.floor, self.object.room_number]
        )

room/templates/room/room_detail.html
{% load room_custom_filters %}
<h2 data-room-id="{{room.room_number}}" id="room-number">Room : {{room.room_number}}</h2>
<a href="{% url 'room:room-list' room.floor %}">Back</a>
<hr>
<h2>Floor : {{room.floor|parse_floor}}</h2>
<h2>Type : {{room.type|parse_type}}</h2>
<h2>AC : {{room.ac|yesno:"Yes,No"}}</h2>
<h2>Status : {{room.occupied|yesno:"Occupied,Vaccant"}}</h2>
<h2>Rent : {{room.rent}}</h2>
{% if not user.is_admin %}
    <br>
    <button type="submit" id="booking-button" {% if room.occupied %} disabled {% endif %}>Book</button>
{% endif %}
<hr>
{% if user.is_admin %}
    <a href="{% url 'room:room-update-admin' room.floor room.room_number %}">Update this room</a>
{% else %}
    {% csrf_token %}
    <script>
        const bookingButton = document.getElementById("booking-button")
        bookingButton.addEventListener("click",function(){
            createBooking()
        })
        function createBooking() {
            var url = "/core/create-booking/"
            var csrfToken = document.querySelector('input[name=csrfmiddlewaretoken]').value
            var roomNumber =  document.getElementById("room-number").getAttribute("data-room-id")
            fetch(url,{
                method:"POST",
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrfToken
                },
                body: JSON.stringify({"room_number":roomNumber})
            })
                .then((response) => response.json())
                .then((data) => {
                console.log(data)
                if(data.redirect) {
                    window.location.href = data.redirect_url
                }
            })
                .catch((error) => {
                console.log(error)
            })
        }
    </script>
{% endif %}

room/templates/room/room_list.html
{% load room_custom_filters %}
<h2>Rooms on {{floor|parse_floor}} floor :-</h2>
<a href="{% url 'home:home' %}">Back</a>
<hr>
{% for room in room_list %}
    <h1><a href="{% url 'room:room-detail' room.floor room.room_number %}">{{room.room_number}}</a></h2>
{% endfor %}
<hr>
{% if user.is_admin %}
    <a href="{% url 'room:room-add-admin' floor %}">Add a room</a>
{% endif %}